version: "2"
linters:
  enable:
    - bodyclose
    - canonicalheader
    - contextcheck
    - containedctx
    - copyloopvar
    - decorder
    - dupword
    - dupl
    - staticcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - goconst
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - gosec
    - unused
    - importas
    - nilerr
    - iface
    - nilnil
    - predeclared
    - reassign
    - recvcheck
    - unconvert
    - usestdlibvars
    - whitespace
    - wastedassign
    - zerologlint
    - tagalign
    - exhaustruct
    - durationcheck
    - embeddedstructfieldcheck
    - godot
    - govet
    - intrange
    - mirror
  settings:
    staticcheck:
      checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022", "-ST1001"]
  # See the dedicated "linters" documentation section.
  exclusions:
    # Mode of the generated files analysis.
    #
    # - `strict`: sources are excluded by strictly following the Go generated file convention.
    #    Source files that have lines matching only the following regular expression will be excluded: `^// Code generated .* DO NOT EDIT\.$`
    #    This line must appear before the first non-comment, non-blank text in the file.
    #    https://go.dev/s/generatedcode
    # - `lax`: sources are excluded if they contain lines like `autogenerated file`, `code generated`, `do not edit`, etc.
    # - `disable`: disable the generated files exclusion.
    #
    # Default: strict
    generated: lax
    # Log a warning if an exclusion rule is unused.
    # Default: false
    warn-unused: true
formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gofmt
    - goimports
    - golines
  exclusions:
    # Log a warning if an exclusion path is unused.
    # Default: false
    warn-unused: true
    # Mode of the generated files analysis.
    #
    # - `strict`: sources are excluded by strictly following the Go generated file convention.
    #    Source files that have lines matching only the following regular expression will be excluded: `^// Code generated .* DO NOT EDIT\.$`
    #    This line must appear before the first non-comment, non-blank text in the file.
    #    https://go.dev/s/generatedcode
    # - `lax`: sources are excluded if they contain lines like `autogenerated file`, `code generated`, `do not edit`, etc.
    # - `disable`: disable the generated files exclusion.
    #
    # Default: lax
    generated: lax
    # Which file paths to exclude.
    # This option is ignored when using `--stdin` as the path is unknown.
    # Default: []
  settings:
    golines:
      # Default: true
      reformat-tags: false
